export const BookstActionTypes = {
  GET_BOOKS: 'GET_BOOKS',
  ADD_BOOK: 'ADD_BOOK',
  SET_CURRENTTAB: 'SET_TAB',
  GET_REQUEST: 'GET_REQUEST',
  CREATE_BOOK_REQUEST: 'CREATE_BOOK_REQUEST',
  UPDATE_BOOK_REQUEST: 'UPDATE_BOOK_REQUEST',
  FILTER_BOOK_REQUEST: 'FILTER_BOOK_REQUEST',
  RESET_FILTERED_RESULT: 'RESET_FILTERED_RESULT',
};
