export const BookstActionTypes = {
  GET_BOOKS: 'GET_BOOKS',
  ADD_BOOK: 'ADD_BOOK',
  SET_CURRENTTAB: 'SET_TAB',
  GET_REQUEST: 'GET_REQUEST',
  CREATE_BOOK_REQUEST: 'CREATE_BOOK_REQUEST',
  UPDATE_BOOK_REQUEST: 'UPDATE_BOOK_REQUEST',
  // REJECT_BOOK_REQUEST: 'REJECT_BOOK_REQUEST',
  // CANCEL_BOOK_REQUEST: 'CANCEL_BOOK_REQUEST',
};
